datebook/urls.py
# -*- coding: utf-8 -*-
"""
Root url's map for application
"""
from django.conf.urls import *

from datebook.views import IndexView
from datebook.views.author import DatebookAuthorView
from datebook.views.year import DatebookYearView
from datebook.views.month import DatebookMonthView, DatebookMonthGetOrCreateView, DatebookMonthCurrentView, DatebookMonthFormView, DatebookNotesFormView
from datebook.views.day import DayEntryFormCreateView, DayEntryDetailView, DayEntryFormEditView, DayEntryCurrentView, DayEntryDeleteFormView
from datebook.views.daymodel import DayModelListView, DayEntryToDayModelFormView, DayModelFormEditView

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    
    url(r'^create/$', DatebookMonthFormView.as_view(), name='create'),
    
    url(r'^(?P<author>\w+)/$', DatebookAuthorView.as_view(), name='author-detail'),
    
    url(r'^(?P<author>\w+)/day-models/$', DayModelListView.as_view(), name='day-models'),
    url(r'^(?P<author>\w+)/day-models/(?P<pk>\d+)/$', DayModelFormEditView.as_view(), name='day-model-edit'),
    
    url(r'^(?P<author>\w+)/current-day/$', DayEntryCurrentView.as_view(), name='current-day'),
    url(r'^(?P<author>\w+)/current-month/$', DatebookMonthCurrentView.as_view(), name='current-month'),
    
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/$', DatebookYearView.as_view(), name='year-detail'),
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/add/(?P<month>\d{1,2})/$', DatebookMonthGetOrCreateView.as_view(), name='month-add'),
    
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/$', DatebookMonthView.as_view(), name='month-detail'),
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/notes/$', DatebookNotesFormView.as_view(), name='month-notes'),
    
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/add/(?P<day>\d{1,2})/$', DayEntryFormCreateView.as_view(), name='day-add'),
    
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', DayEntryDetailView.as_view(), name='day-detail'),
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/edit/$', DayEntryFormEditView.as_view(), name='day-edit'),
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/remove/$', DayEntryDeleteFormView.as_view(), name='day-remove'),
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/to-daymodel/$', DayEntryToDayModelFormView.as_view(), name='dayentry-to-daymodel'),
)

datebook/models.py
# -*- coding: utf-8 -*-
"""
Data models
"""
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now as tz_now, localtime

from datebook import utils

class Datebook(models.Model):
    """
    Datebook is only for one user (its author) and it is not shared.

    A Datebook is for a specific month of a year.

    A Datebook is alike "lazy" in the way that its 'DayEntry' are only created
    when the user fill them and so Datebook are not initialized with all its
    month's days when created.
    """
    author = models.ForeignKey(User, verbose_name=_('author'))
    created = models.DateTimeField(_('created'), blank=True, editable=False)
    modified = models.DateTimeField(_('last edit'), auto_now=True)
    period = models.DateField(_("month of activity"), blank=False)
    notes = models.TextField(_("content"), max_length=500, blank=True)

    def __unicode__(self):
        return self.period.strftime("%B %Y")

    @models.permalink
    def get_absolute_url(self):
        return ('datebook:month-detail', (), {
            'author': self.author.username,
            'year': self.period.year,
            'month': self.period.strftime('%m'),
        })

    def clean(self):
        """Allways forcing to the first day of the month"""
        self.period = self.period.replace(day=1)

    def save(self, *args, **kwargs):
        # First create
        if not self.created:
            self.created = tz_now()

        super(Datebook, self).save(*args, **kwargs)

    class Meta:
        unique_together = ("author", "period")
        verbose_name = _("Datebook")
        verbose_name_plural = _("Datebooks")


class DayBase(models.Model):
    """
    Base day model
    """
    content = models.TextField(_("content"), max_length=500, blank=True)

    start = models.DateTimeField(_('start'), blank=False) # should default to something like 9h with the dayentry date
    stop = models.DateTimeField(_('stop'), blank=False) # should default to something like 19h with the dayentry date
    pause = models.TimeField(_('pause'), blank=False, default=datetime.time(0, 0))
    overtime = models.TimeField(_('overtime'), blank=False, default=datetime.time(0, 0))

    def get_display_hour(self, timeobj):
        """Formating time "XXhYY" display, minutes are not displayed if they are not > 0"""
        _m = ""
        timeobj = localtime(timeobj)
        if timeobj.minute > 0:
            _m = str(timeobj.minute).rjust(2, "0")
        return _('%(hour)sh%(minute)s') % {'hour': str(timeobj.hour).rjust(2, "0"), 'minute': _m}

    def get_working_hours(self):
        """Display working hours like: '08h to 18h59'"""
        return _('%(start)s to %(stop)s') % {'start': self.get_display_hour(self.start), 'stop': self.get_display_hour(self.stop)}

    def get_elapsed_seconds(self):
        """Return elapsed seconds between start and stop, where pause time has been substracted from"""
        return utils.timedelta_to_seconds((self.stop-self.start))-utils.time_to_seconds(self.pause)

    def get_elapsed_time(self):
        """Return formatted clock for elapsed seconds from 'get_elapsed_seconds'"""
        return utils.format_seconds_to_clock(self.get_elapsed_seconds())

    def get_overtime_seconds(self):
        """Return overtime seconds"""
        return utils.time_to_seconds(self.overtime)

    def get_overtime_time(self):
        """Return formatted clock for overtime seconds from 'get_overtime_seconds'"""
        return utils.format_seconds_to_clock(self.get_overtime_seconds())

    #def clean(self):
        ##DEPRECATED: Stuff below are for the form controller
        #from django.core.exceptions import ValidationError
        ## Stop can't be less than start
        #if self.stop < self.start:
            #raise ValidationError(_("Hour stop can't be less than hour start."))
        ## TODO: Pause time can't be superior to the time of (stop-start)

    class Meta:
        abstract = True


class DayEntry(DayBase):
    """
    Activity day in a Datebook
    """
    datebook = models.ForeignKey(Datebook, verbose_name=_('datebook'))
    activity_date = models.DateField(_('activity day date'), blank=False) # inherit month and year from its Datebook
    vacation = models.BooleanField(_('vacation'), default=False, blank=True, null=False)

    def __unicode__(self):
        if not self.activity_date:
            return _("Empty")
        return self.activity_date.strftime("%d/%m/%Y")

    def clean(self):
        # Inherit the year and month from its datebook
        if hasattr(self, 'datebook'):
            self.activity_date = self.activity_date.replace(month=self.datebook.period.month, year=self.datebook.period.year)

    def save(self, *args, **kwargs):
        # Allways update the datebook
        self.datebook.modified = tz_now()
        self.datebook.save()

        super(DayEntry, self).save(*args, **kwargs)

    class Meta:
        unique_together = ("datebook", "activity_date")
        verbose_name = _("day entry")
        verbose_name_plural = _("day entries")


class DayModel(DayBase):
    """
    Day model from an user
    """
    author = models.ForeignKey(User, verbose_name=_('author'))
    title = models.CharField(_("title"), blank=False, max_length=255)

    def __unicode__(self):
        return self.title

    class Meta:
        unique_together = ("author", "title")
        verbose_name = _("day model")
        verbose_name_plural = _("day models")

datebook/forms/month.py
# -*- coding: utf-8 -*-
"""
Forms for month forms
"""
from django.conf import settings
from django import forms
from django.utils.translation import ugettext as _

from crispy_forms.helper import FormHelper

from datebook.models import Datebook
from datebook.forms import CrispyFormMixin
from datebook.utils.imports import safe_import_module

class DatebookForm(CrispyFormMixin, forms.Form):
    """
    Datebook form
    """
    crispy_form_helper_path = 'datebook.forms.crispies.month_helper'
    
    def __init__(self, *args, **kwargs):
        self.available_users = kwargs.pop('available_users', [])
        super(DatebookForm, self).__init__(*args, **kwargs)
        super(forms.Form, self).__init__(*args, **kwargs)
        
        self.fields['owner'] = forms.ModelChoiceField(label=_('owner'), queryset=self.available_users, empty_label=None)
        self.fields['period'] = forms.DateField(label=_('period'))
    
    def clean_period(self):
        period = self.cleaned_data['period']
        period = period.replace(day=1)
        
        return period
    
    def save(self, *args, **kwargs):
        instance = Datebook(
            author=self.cleaned_data['owner'],
            period=self.cleaned_data['period']
        )
        instance.save()
        
        return instance


class DatebookNotesForm(CrispyFormMixin, forms.ModelForm):
    """
    Datebook form
    """
    crispy_form_helper_path = 'datebook.forms.crispies.notes_helper'
    
    def __init__(self, *args, **kwargs):
        super(DatebookNotesForm, self).__init__(*args, **kwargs)
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        
        # Set the form field for Datebook.notes
        field_helper = safe_import_module(settings.DATEBOOK_TEXT_FIELD_HELPER_PATH)
        if field_helper is not None:
            self.fields['notes'] = field_helper(self, **{'label':_('notes'), 'required':True})
    
    def clean_notes(self):
        """
        Text content validation
        """
        notes = self.cleaned_data.get("notes")
        validation_helper = safe_import_module(settings.DATEBOOK_TEXT_VALIDATOR_HELPER_PATH)
        if validation_helper is not None:
            return validation_helper(self, notes)
        else:
            return notes
    
    class Meta:
        model = Datebook
        fields = ['notes']

datebook/templates/datebook/month/calendar.html
{% extends "datebook/base.html" %}
{% load i18n autobreadcrumb crispy_forms_tags %}
{% load cycle from future %}

{% block datebook_container_css_classes %} large-row-fluid{% endblock %}


{% block head_base_js %}{{ block.super }}
<script type="text/javascript">
//<![CDATA[
$(document).ready(function($) {
    // Switch calendar to mosaic/flat view
    $('#datebook-view-mode').calendar_view_mode();

    // Navigation within reveal modal for next/previous day
    $("body").calendar_days_modalnav();

    // Daymodels menu chooser
    $('#daymodels-menu').calendar_daymodel_form({
        'overlay_selector': ".daymodel-choose-overlay",
        'form_selector': "#daymodel-menu-chooser-form",
        'day_field_selector': "#id_days",
        'daymodel_field_selector': "#id_daymodel"
    });
});
//]]>
</script>
{% endblock %}


{% block datebook_maintitle %}
<div class="row row-fluid">
    <div class="large-10 columns">
        <h2>{% current_title_from_breadcrumbs %}</h2>
    </div>
    <div class="large-2 columns">
        {% comment %}View mode menu{% endcomment %}
        <ul class="button-group gregarious round" id="datebook-view-mode">
            <li><a href="#" class="button tiny to-mosaic" id="datebook-switch-to-mosaic" title="{% trans "Calendar view" %}"><i class="icon-calendar"></i></a></li>
            <li><a href="#" class="button tiny secondary to-flat" id="datebook-switch-to-flat" title="{% trans "Flat view" %}"><i class="icon-list-ul"></i></a></li>
        </ul>
    </div>
</div>
{% endblock %}


{% block datebook_content %}
<div class="row row-fluid">

    <div class="large-2 large-push-10 columns">
        <div class="clearfix">
            {% comment %}Weeks stats{% endcomment %}
            <table class="calendar-time-infos">
                <thead>
                    <tr>
                        <th class="text-center">{% trans "Week" %}</th>
                        <th class="text-center"><i class="icon-history" title="{% trans "Elapsed" %}"></i></th>
                        <th class="text-center"><i class="icon-star-full" title="{% trans "Overtime" %}"></i></th>
                        <th class="text-center"><i class="icon-sunumbrella" title="{% trans "Vacations" %}"></i></th>
                    </tr>
                </thead>
                <tbody>
                {% for week in datebook_calendar.weeks_totals %}
                    <tr>
                        <th class="text-right">{{ forloop.counter }}</th>
                        <td class="text-center">
                            {% blocktrans with time_clock=week.elapsed_time %}{{ time_clock }}h{% endblocktrans %}
                        </td>
                        <td class="text-center">
                            {% blocktrans with time_clock=week.overtime_time %}{{ time_clock }}h{% endblocktrans %}
                        </td>
                        <td class="text-center">
                            {% blocktrans with counter=week.vacations %}{{ counter }}d{% endblocktrans %}
                        </td>
                    </tr>
                {% endfor %}
                    <tr class="month_total">
                        <th class="text-right">{% trans "Total" %}</th>
                        <td class="text-center">
                            {% blocktrans with time_clock=datebook_calendar.elapsed_time %}{{ time_clock }}h{% endblocktrans %}
                        </td>
                        <td class="text-center">
                            {% if datebook_calendar.overtime_seconds > 0 %}
                                {% blocktrans with time_clock=datebook_calendar.overtime_time %}{{ time_clock }}h{% endblocktrans %}
                            {% else %}
                                {% blocktrans with time_clock=0 %}{{ time_clock }}h{% endblocktrans %}
                            {% endif %}
                        </td>
                        <td class="text-center">
                            {% if datebook_calendar.vacations > 0 %}
                                {% blocktrans with counter=datebook_calendar.vacations %}{{ counter }}d{% endblocktrans %}
                            {% else %}
                                {% blocktrans with counter=0 %}{{ counter }}d{% endblocktrans %}
                            {% endif %}
                        </td>
                </tbody>
            </table>

            {% if user == author or user.is_superuser or perms.datebook.change_dayentry %}
            <hr>
            {% comment %}Daymodel menu chooser{% endcomment %}
            <ul class="button-group gregarious" id="daymodels-menu">
                <li class="opener"><a href="#" class="button tiny"><i class="icon-insert-template"></i> {% blocktrans %}Use models{% endblocktrans %}</a></li>
                <li class="closer" style="display:none"><a href="#" class="button secondary tiny"><i class="icon-times-circle"></i> {% blocktrans %}Close models{% endblocktrans %}</a></li>
                <li class="form" style="display:none">
                    {% crispy daymodels_form %}
                </li>
            </ul>{% endif %}
        </div>

        <hr>
        <div class="calendar-notes-container">
            <h3>{% trans "Notes" %}</h3>
            {% if datebook.notes %}
                <div class="content">{% if DATEBOOK_TEXT_MARKUP_RENDER_TEMPLATE %}
                    {% include DATEBOOK_TEXT_MARKUP_RENDER_TEMPLATE with content=datebook.notes %}
                {% else %}
                    {{ datebook.notes|linebreaks }}
                {% endif %}</div>
            {% else %}
                <p class="empty text-center">{% trans "Empty" %}</p>
            {% endif %}
            {% if user == author or user.is_superuser or perms.datebook.change_datebook %}
            <a href="{% url 'datebook:month-notes' author=author year=datebook.period.year month=datebook.period.month %}" class="button expand"><i class="icon-pencil"></i> {% blocktrans %}Edit{% endblocktrans %}</a>
            {% endif %}
        </div>

    </div>

    <div class="large-10 large-pull-2 columns">

        {% comment %}The Month calendar{% endcomment %}
        <div class="datebook-month calendar">
            {% comment %}Week day names{% endcomment %}
            <div class="head">
                {% spaceless %}
                    <span class="weekno"></span>
                    {% for classname, name in datebook_calendar.weekheader %}
                    <span class="{% cycle 'mon' 'tue' 'wed' 'thu' 'fri' 'sat' 'sun' %}">{% trans name %}</span>
                    {% endfor %}
                {% endspaceless %}
            </div>

            {% spaceless %}
            {% for week in datebook_calendar.month %}
            <div class="week">
                <div class="item weekno">
                    <span class="label radius">{% trans "Week" %}&nbsp;{{ forloop.counter }}</span>
                </div>
                {% comment %}Days looping on the calendar object{% endcomment %}
                {% for day in week %}
                    {% cycle 'mon' 'tue' 'wed' 'thu' 'fri' 'sat' 'sun' as day_name silent %}
                    <div class="item {{ day_name }}{% if day.entry %} has-entry{% if day.entry.vacation %} vacation{% endif %}{% endif %}{% if day.is_current %} current{% endif %}{% if day.noday %} noday{% endif %}{% if day.entry.projected %} projected{% endif %}"
                    {% if not day.noday %}
                    data-date="{{ day.date.day }}"
                    id="{{ day_name }}-{{ day.date.day }}"{% endif %}
                    >
                        {% if not day.noday %}
                            <h3>{{ day.date|date:"l d F" }}</h3>
                            <div class="container">
                                {% if day.entry %}
                                    {% if day.entry.vacation %}
                                        <p class="vacation-label">{% trans "Vacation" %}</p>
                                    {% else %}
                                        <ul class="inline-list time-infos">
                                            {% if not day.entry.projected %}
                                            <li><span class="label round secondary"><i class="icon-history"></i> {{ day.entry.get_working_hours }}</span></li>
                                            <li><span class="label round secondary"><i class="icon-hour-glass"></i> {{ day.entry.get_elapsed_time }}</span></li>
                                            {% if day.entry.get_overtime_seconds > 0 %}<li><span class="label round secondary"><i class="icon-star-full"></i> {{ day.entry.get_overtime_time }}</span></li>{% endif %}
                                            {% else %}
                                            <li><span class="label round secondary"><i class="icon-binoculars"></i> {% blocktrans with time_clock=day.entry.get_elapsed_time %}Expectation: {{ time_clock }}{% endblocktrans %}</span></li>
                                            {% endif %}
                                        </ul>
                                        {% if day.entry.content %}
                                            <div class="content restructuredtext">{% if DATEBOOK_TEXT_MARKUP_RENDER_TEMPLATE %}
                                                {% include DATEBOOK_TEXT_MARKUP_RENDER_TEMPLATE with content=day.entry.content %}
                                            {% else %}
                                                {{ day.entry.content|linebreaks }}
                                            {% endif %}</div>
                                        {% else %}
                                            <p class="empty">{% trans "Empty content" %}</p>
                                        {% endif %}
                                    {% endif %}
                                {% else %}
                                    {% if user == author or user.is_superuser or perms.datebook.add_dayentry %}
                                        {% url 'datebook:day-add' author=author year=datebook.period.year month=datebook.period.month day=day.date.day as add_url %}
                                        <p class="empty">{% blocktrans with add_url=add_url %}There is no entry yet, <a href="{{ add_url }}">add it</a>{% endblocktrans %}</p>
                                    {% else %}
                                        <p class="empty">{% blocktrans %}There is no entry yet{% endblocktrans %}</p>
                                    {% endif %}
                                {% endif %}
                            </div>

                            {% if day.entry %}
                            <div class="menu">
                                <a title="{% trans 'Read' %}" class="read action" href="{% url 'datebook:day-detail' author=author year=datebook.period.year month=datebook.period.month day=day.date.day %}" data-reveal-id="revealDayModal" data-reveal-ajax="true">
                                    <i class="icon-eye"></i>
                                </a>
                                {% if user == author or user.is_superuser or perms.datebook.change_dayentry %}
                                    <a title="{% trans 'Edit' %}" class="edit action" href="{% url 'datebook:day-edit' author=author year=datebook.period.year month=datebook.period.month day=day.date.day %}"{% comment %} data-reveal-id="revealDayModal" data-reveal-ajax="true"{% endcomment %}>
                                        <i class="icon-pencil"></i>
                                    </a>
                                {% endif %}
                            </div>
                            {% elif user == author or user.is_superuser or perms.datebook.add_dayentry %}
                            <div class="menu">
                                <a title="{% trans 'Add' %}" class="add action" href="{{ add_url }}">
                                    <i class="icon-plus-circle"></i>
                                </a>
                            </div>
                            {% endif %}
                            {% comment %}
                                Overlay to select item for daymodel assignment
                            {% endcomment %}
                            <div class="daymodel-choose-overlay" style="display:none" data-day-date="{{ day.date.day }}"><div class="inner">
                                {% comment %}<p>Fill this day</p>{% endcomment %}
                                <p class="checkbox-action"><i class="icon-square-o unchecked"></i><i class="icon-check-square-o checked"></i></p>
                            </div></div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            {% endfor %}
            {% endspaceless %}

        </div>


        <div class="legend clearfix text-right">
            <ul class="inline-list right">
                <li><strong>{% trans "Legend:" %}</strong></li>
                <li><i class="icon-history" title="{% trans "Elapsed" %}">&nbsp;{% trans "Elapsed" %}</i></li>
                <li><i class="icon-hour-glass" title="{% trans "Pause" %}">&nbsp;{% trans "Pause" %}</i></li>
                <li><i class="icon-star-full" title="{% trans "Overtime" %}">&nbsp;{% trans "Overtime" %}</i></li>
                <li><i class="icon-sunumbrella" title="{% trans "Vacations" %}">&nbsp;{% trans "Vacations" %}</i></li>
            </ul>
        </div>

    </div>
</div>

{% endblock %}

{% block foot_more_js %}<div id="revealDayModal" class="reveal-modal medium" data-reveal="true"></div>{% endblock %}

datebook/templates/datebook/month/form.html
{% extends "datebook/base.html" %}
{% load i18n crispy_forms_tags %}

{% block head_base_js %}{{ block.super }}
    <script type="text/javascript">
    //<![CDATA[
    $(document).ready(function() {
        var picker = new Pikaday({
            field: $('#id_period')[0],
            //format: 'YYYY-MM-DD',
            format: 'DD/MM/YYYY',
            i18n: {
                months        : ['{% trans "January" %}','{% trans "February" %}','{% trans "March" %}','{% trans "April" %}','{% trans "May" %}','{% trans "June" %}','{% trans "July" %}','{% trans "August" %}','{% trans "September" %}','{% trans "October" %}','{% trans "November" %}','{% trans "December" %}'],
                weekdays      : ['{% trans "Sunday" %}','{% trans "Monday" %}','{% trans "Tuesday" %}','{% trans "Wednesday" %}','{% trans "Thursday" %}','{% trans "Friday" %}','{% trans "Saturday" %}'],
                weekdaysShort : ['{% trans "Sun" %}','{% trans "Mon" %}','{% trans "Tue" %}','{% trans "Wed" %}','{% trans "Thu" %}','{% trans "Fri" %}','{% trans "Sat" %}']
            }
        });
    });
    //]]>
    </script>
{% endblock %}

{% block datebook_content %}
{% if form %}
    {% crispy form %}
{% else %}
    <p class="empty text-center">{% blocktrans %}There is no user without a datebook{% endblocktrans %}</p>
{% endif %}
{% endblock %}

datebook/templates/datebook/month/notes_form.html
{% extends "datebook/base.html" %}
{% load i18n crispy_forms_tags %}

{% block head_base_js %}{{ block.super }}{% if DATEBOOK_TEXT_FIELD_JS_TEMPLATE and form.notes %}
    {% include DATEBOOK_TEXT_FIELD_JS_TEMPLATE with field=form.notes %}
{% endif %}{% endblock %}

{% block datebook_content %}
    {% crispy form %}
{% endblock %}