datebook/urls.py
# -*- coding: utf-8 -*-
"""
Root url's map for application
"""
from django.conf.urls import *

from datebook.views import IndexView
from datebook.views.author import DatebookAuthorView
from datebook.views.year import DatebookYearView
from datebook.views.month import DatebookMonthView, DatebookMonthGetOrCreateView, DatebookMonthCurrentView, DatebookMonthFormView, DatebookNotesFormView
from datebook.views.day import DayEntryFormCreateView, DayEntryDetailView, DayEntryFormEditView, DayEntryCurrentView, DayEntryDeleteFormView
from datebook.views.daymodel import DayModelListView, DayEntryToDayModelFormView, DayModelFormEditView

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    
    url(r'^create/$', DatebookMonthFormView.as_view(), name='create'),
    
    url(r'^(?P<author>\w+)/$', DatebookAuthorView.as_view(), name='author-detail'),
    
    url(r'^(?P<author>\w+)/day-models/$', DayModelListView.as_view(), name='day-models'),
    url(r'^(?P<author>\w+)/day-models/(?P<pk>\d+)/$', DayModelFormEditView.as_view(), name='day-model-edit'),
    
    url(r'^(?P<author>\w+)/current-day/$', DayEntryCurrentView.as_view(), name='current-day'),
    url(r'^(?P<author>\w+)/current-month/$', DatebookMonthCurrentView.as_view(), name='current-month'),
    
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/$', DatebookYearView.as_view(), name='year-detail'),
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/add/(?P<month>\d{1,2})/$', DatebookMonthGetOrCreateView.as_view(), name='month-add'),
    
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/$', DatebookMonthView.as_view(), name='month-detail'),
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/notes/$', DatebookNotesFormView.as_view(), name='month-notes'),
    
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/add/(?P<day>\d{1,2})/$', DayEntryFormCreateView.as_view(), name='day-add'),
    
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', DayEntryDetailView.as_view(), name='day-detail'),
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/edit/$', DayEntryFormEditView.as_view(), name='day-edit'),
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/remove/$', DayEntryDeleteFormView.as_view(), name='day-remove'),
    url(r'^(?P<author>\w+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/to-daymodel/$', DayEntryToDayModelFormView.as_view(), name='dayentry-to-daymodel'),
)

datebook/models.py
# -*- coding: utf-8 -*-
"""
Data models
"""
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now as tz_now, localtime

from datebook import utils

class Datebook(models.Model):
    """
    Datebook is only for one user (its author) and it is not shared.

    A Datebook is for a specific month of a year.

    A Datebook is alike "lazy" in the way that its 'DayEntry' are only created
    when the user fill them and so Datebook are not initialized with all its
    month's days when created.
    """
    author = models.ForeignKey(User, verbose_name=_('author'))
    created = models.DateTimeField(_('created'), blank=True, editable=False)
    modified = models.DateTimeField(_('last edit'), auto_now=True)
    period = models.DateField(_("month of activity"), blank=False)
    notes = models.TextField(_("content"), max_length=500, blank=True)

    def __unicode__(self):
        return self.period.strftime("%B %Y")

    @models.permalink
    def get_absolute_url(self):
        return ('datebook:month-detail', (), {
            'author': self.author.username,
            'year': self.period.year,
            'month': self.period.strftime('%m'),
        })

    def clean(self):
        """Allways forcing to the first day of the month"""
        self.period = self.period.replace(day=1)

    def save(self, *args, **kwargs):
        # First create
        if not self.created:
            self.created = tz_now()

        super(Datebook, self).save(*args, **kwargs)

    class Meta:
        unique_together = ("author", "period")
        verbose_name = _("Datebook")
        verbose_name_plural = _("Datebooks")


class DayBase(models.Model):
    """
    Base day model
    """
    content = models.TextField(_("content"), max_length=500, blank=True)

    start = models.DateTimeField(_('start'), blank=False) # should default to something like 9h with the dayentry date
    stop = models.DateTimeField(_('stop'), blank=False) # should default to something like 19h with the dayentry date
    pause = models.TimeField(_('pause'), blank=False, default=datetime.time(0, 0))
    overtime = models.TimeField(_('overtime'), blank=False, default=datetime.time(0, 0))

    def get_display_hour(self, timeobj):
        """Formating time "XXhYY" display, minutes are not displayed if they are not > 0"""
        _m = ""
        timeobj = localtime(timeobj)
        if timeobj.minute > 0:
            _m = str(timeobj.minute).rjust(2, "0")
        return _('%(hour)sh%(minute)s') % {'hour': str(timeobj.hour).rjust(2, "0"), 'minute': _m}

    def get_working_hours(self):
        """Display working hours like: '08h to 18h59'"""
        return _('%(start)s to %(stop)s') % {'start': self.get_display_hour(self.start), 'stop': self.get_display_hour(self.stop)}

    def get_elapsed_seconds(self):
        """Return elapsed seconds between start and stop, where pause time has been substracted from"""
        return utils.timedelta_to_seconds((self.stop-self.start))-utils.time_to_seconds(self.pause)

    def get_elapsed_time(self):
        """Return formatted clock for elapsed seconds from 'get_elapsed_seconds'"""
        return utils.format_seconds_to_clock(self.get_elapsed_seconds())

    def get_overtime_seconds(self):
        """Return overtime seconds"""
        return utils.time_to_seconds(self.overtime)

    def get_overtime_time(self):
        """Return formatted clock for overtime seconds from 'get_overtime_seconds'"""
        return utils.format_seconds_to_clock(self.get_overtime_seconds())

    #def clean(self):
        ##DEPRECATED: Stuff below are for the form controller
        #from django.core.exceptions import ValidationError
        ## Stop can't be less than start
        #if self.stop < self.start:
            #raise ValidationError(_("Hour stop can't be less than hour start."))
        ## TODO: Pause time can't be superior to the time of (stop-start)

    class Meta:
        abstract = True


class DayEntry(DayBase):
    """
    Activity day in a Datebook
    """
    datebook = models.ForeignKey(Datebook, verbose_name=_('datebook'))
    activity_date = models.DateField(_('activity day date'), blank=False) # inherit month and year from its Datebook
    vacation = models.BooleanField(_('vacation'), default=False, blank=True, null=False)

    def __unicode__(self):
        if not self.activity_date:
            return _("Empty")
        return self.activity_date.strftime("%d/%m/%Y")

    def clean(self):
        # Inherit the year and month from its datebook
        if hasattr(self, 'datebook'):
            self.activity_date = self.activity_date.replace(month=self.datebook.period.month, year=self.datebook.period.year)

    def save(self, *args, **kwargs):
        # Allways update the datebook
        self.datebook.modified = tz_now()
        self.datebook.save()

        super(DayEntry, self).save(*args, **kwargs)

    class Meta:
        unique_together = ("datebook", "activity_date")
        verbose_name = _("day entry")
        verbose_name_plural = _("day entries")


class DayModel(DayBase):
    """
    Day model from an user
    """
    author = models.ForeignKey(User, verbose_name=_('author'))
    title = models.CharField(_("title"), blank=False, max_length=255)

    def __unicode__(self):
        return self.title

    class Meta:
        unique_together = ("author", "title")
        verbose_name = _("day model")
        verbose_name_plural = _("day models")

datebook/forms/year.py
# -*- coding: utf-8 -*-
"""
Forms for year forms
"""
import datetime

from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms_foundation.layout import Submit

from datebook.models import Datebook
from datebook.forms import CrispyFormMixin

class DatebookYearForm(CrispyFormMixin, forms.Form):
    """
    Datebook year form
    """
    crispy_form_helper_path = 'datebook.forms.crispies.year_helper'
    
    def __init__(self, author, queryset, *args, **kwargs):
        self.author = author
        
        super(DatebookYearForm, self).__init__(*args, **kwargs)
        super(forms.Form, self).__init__(*args, **kwargs)
        
        self.today = datetime.date.today()
        existing_years = [item.year for item in queryset]
        available_years = [(k, k) for k in range(self.today.year-3, self.today.year+4) if k not in existing_years]
        
        self.fields['year'] = forms.ChoiceField(label=_('year'), choices=available_years)
    
    def save(self, *args, **kwargs):
        year = int(self.cleaned_data['year'])
        # Default opened datebook is for the first month of the given year
        period = [year, 1, 1]
        # Open the datebook for the current month if the given year is the current year
        if year == self.today.year:
            period = [year, self.today.month, 1]
            
        instance = Datebook(
            author=self.author,
            period=datetime.date(*period)
        )
        instance.save()
        
        return instance

datebook/views/week.py
# -*- coding: utf-8 -*-
"""
Datebook week views

DEPRECATED
"""
import calendar

from django import http
from django.views import generic

from braces.views import LoginRequiredMixin

from datebook.mixins import DatebookCalendarMixin

class DatebookWeekView(LoginRequiredMixin, DatebookCalendarMixin, generic.TemplateView):
    """
    Datebook month week details view
    
    Get the week days from the calendar for the given year+month then merge it with 
    associated day entries
    """
    template_name = "datebook/week.html"
    
    def find_weekday_range(self):
        # week number is indexed on 1 in urls, but we use it at a position item in 
        # returned list, so we turn it to indexed on 0
        week = self.week-1
        
        try:
            weekdays = calendar.Calendar().monthdatescalendar(self.year, self.month)[week]
        except IndexError:
            raise http.Http404
        
        # Calendar fill the grid with previous or past month days, so we filter them to 
        # return only the current month days
        _f = lambda x: x.year == self.year and x.month == self.month
        return filter(_f, weekdays)
    
    def get_dayentry_list(self, *args, **kwargs):
        """Improve the queryset to get only the days for the given week"""
        if len(self.weekdays)>1:
            _f = {'activity_date__gte': self.weekdays[0], 'activity_date__lte': self.weekdays[-1]}
        else:
            _f = {'activity_date': self.weekdays[0]}
        return super(DatebookWeekView, self).get_dayentry_list(_f)
    
    def get_context_data(self, **kwargs):
        context = super(DatebookWeekView, self).get_context_data(**kwargs)
        
        # Filter query set on the week days
        self.weekdays = self.find_weekday_range()
        dayentry_list = self.get_dayentry_list()
        # Make an empty dict (index on date) of weekdays
        _w = dict(map(lambda x: (x, None), self.weekdays))
        # Make a dict from the day entry and merge it in the weekdays
        _w.update(dict(map(lambda x: (x.activity_date, x), dayentry_list)))
        
        context.update({
            'datebook': self.object,
            'week': self.week,
            # For django templates loop we need to have a sorted list
            'weekdays': [(key, _w[key]) for key in sorted(_w.iterkeys())],
        })
        return context
    
    def get(self, request, *args, **kwargs):
        # Week number can't be empty or zero (index on 1 for humans)
        if not self.week:
            raise http.Http404
        
        self.object = self.get_datebook({'period__year': self.year, 'period__month': self.month})
        
        context = self.get_context_data(**kwargs)
        
        return self.render_to_response(context)

datebook/views/year.py
# -*- coding: utf-8 -*-
"""
Datebook year views
"""
import datetime
import calendar

from django.views import generic

from braces.views import LoginRequiredMixin

from datebook.mixins import DateKwargsMixin

class DatebookYearView(LoginRequiredMixin, DateKwargsMixin, generic.TemplateView):
    """
    Datebook year view
    
    Display the twelve months of the given year with link and infos for the 
    existing datebooks
    """
    template_name = "datebook/year.html"
        
    def get_context_data(self, **kwargs):
        context = super(DatebookYearView, self).get_context_data(**kwargs)
        
        _curr = datetime.date.today()
        # Get all datebooks for the given year
        queryset = self.object.datebook_set.filter(period__year=self.year).order_by('period')[0:13]
        _datebook_map = dict(map(lambda x: (x.period.month, x), queryset))
        # Fill the finded datebooks in the month map, month without datebook will have 
        # None instead of a Datebook instance
        datebooks_map = [(datetime.datetime(self.year, i, 1), _datebook_map.get(i)) for i in range(1,13)]
        
        context.update({
            'year_current': _curr.year,
            'is_current_year': (self.year == _curr.year),
            'datebooks_map': datebooks_map,
        })
        return context
    
    def get(self, request, *args, **kwargs):
        self.object = self.author
        
        context = self.get_context_data(**kwargs)
        
        return self.render_to_response(context)

datebook/templates/datebook/author_index.html
{% extends "datebook/base.html" %}
{% load i18n crispy_forms_tags %}

{% block datebook_content %}
{% if form %}
    <div class="clearfix">{% crispy form %}</div>
{% endif %}

<ul class="list-group">
    {% spaceless %}{% for year,year_datetime,months_counter in object_list %}
        <li{% if today.year == year_datetime.year %} class="current"{% endif %}>
            <a href="{% url 'datebook:year-detail' author=author year=year %}">
                <p class="right text-right"><small>
                    {% blocktrans count counter=months_counter %}<strong>{{ counter }}</strong> opened month{% plural %}<strong>{{ counter }}</strong> opened months{% endblocktrans %}
                    </small></p>
                <h3>{{ year }}</h3>
            </a>
        </li>
    {% endfor %}{% endspaceless %}
</ul>{% endblock %}

datebook/templates/datebook/base.html
{% extends "skeleton.html" %}
{% load i18n autobreadcrumb %}

{% block head_title %}{% trans "Datebook" %} - {% current_title_from_breadcrumbs %}{% endblock %}

{% block head_more_links %}{{ block.super }}
    {% include "datebook/include_css.html" %}
{% endblock %}

{% block head_base_js %}{{ block.super }}
    {% include "datebook/include_js.html" %}
{% endblock %}

{% block menu_active_link_datebook %} class="active"{% endblock %}

{% block base_content %}<div class="row datebook{% block datebook_container_css_classes %}{% endblock %}">
    <div class="small-12 columns">
        {% block breadcrumbs_block %}{% autobreadcrumbs_tag %}{% endblock %}
        {% block datebook_maintitle %}<h2>{% current_title_from_breadcrumbs %}</h2>{% endblock %}
        {% block datebook_content %}{% endblock %}
    </div>
</div>{% endblock %}

datebook/templates/datebook/datebook_day_form.html
{% extends "datebook/base.html" %}
{% load autobreadcrumb crispy_forms_tags %}

{% block head_base_js %}{{ block.super }}
<script type="text/javascript">
//<![CDATA[
    $(document).ready(function() {
        init_form("form");
    });
//]]>
</script>
{% endblock %}

{% block datebook_content %}
{% crispy form %}
{% endblock %}

datebook/templates/datebook/datebook_day_fragment.html
{% load i18n %}
<div class="inner">
    <div class="row item {% if object %} has-entry{% if object.vacation %} vacation{% endif %}{% endif %}">
        <div class="small-12 columns">
            <h3 class="text-center">{{ object.activity_date|date:"l d F" }}</h3>
            {% if object %}
                {% if object.vacation %}
                    <p class="empty text-center vacation-label">Vacation</p>
                {% else %}
                    <ul class="inline-list">
                        <li><span class="label round secondary"><i class="icon-clock"></i> {{ object.get_working_hours }}</span></li>
                        <li><span class="label round secondary"><i class="icon-timer"></i> {{ object.get_elapsed_time }}</li>
                    </ul>
                    {% if object.content %}
                        <div class="content">{{ object.content|linebreaks }}</div>
                    {% else %}
                        <p class="empty text-center">Empty content</p>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
        {% if previous_day %}<a 
        href="{% url 'datebook-author-day' author=author year=datebook.period.year month=datebook.period.month day=previous_day.activity_date.day %}" 
        class="button small modal-navigation-day previous" 
        data-from-id="{{ datebook.period.year }}-{{ datebook.period.month }}-{{ object.activity_date.day }}" 
        data-target-id="{{ datebook.period.year }}-{{ datebook.period.month }}-{{ previous_day.activity_date.day }}"
        title="Précédent">
            <i class="icon-arrow-left"></i>
        </a>{% endif %}
        {% if next_day %}<a 
        href="{% url 'datebook-author-day' author=author year=datebook.period.year month=datebook.period.month day=next_day.activity_date.day %}"
        class="button small modal-navigation-day next" 
        data-from-id="{{ datebook.period.year }}-{{ datebook.period.month }}-{{ object.activity_date.day }}" 
        data-target-id="{{ datebook.period.year }}-{{ datebook.period.month }}-{{ next_day.activity_date.day }}"
        title="Suivant">
            <i class="icon-arrow-right"></i>
        </a>{% endif %}
    </div>
    {% comment %}<a class="close-reveal-modal">&#215;</a>{% endcomment %}
</div>

datebook/templates/datebook/datebook_month_form.html
{% extends "datebook/base.html" %}
{% load i18n crispy_forms_tags %}

{% block head_base_js %}{{ block.super }}
    <script type="text/javascript">
    //<![CDATA[
    $(document).ready(function() {
        var picker = new Pikaday({
            field: $('#id_period')[0],
            //format: 'YYYY-MM-DD',
            format: 'DD/MM/YYYY',
            i18n: {
                months        : ['{% trans "January" %}','{% trans "February" %}','{% trans "March" %}','{% trans "April" %}','{% trans "May" %}','{% trans "June" %}','{% trans "July" %}','{% trans "August" %}','{% trans "September" %}','{% trans "October" %}','{% trans "November" %}','{% trans "December" %}'],
                weekdays      : ['{% trans "Sunday" %}','{% trans "Monday" %}','{% trans "Tuesday" %}','{% trans "Wednesday" %}','{% trans "Thursday" %}','{% trans "Friday" %}','{% trans "Saturday" %}'],
                weekdaysShort : ['{% trans "Sun" %}','{% trans "Mon" %}','{% trans "Tue" %}','{% trans "Wed" %}','{% trans "Thu" %}','{% trans "Fri" %}','{% trans "Sat" %}']
            }
        });
    });
    //]]>
    </script>
{% endblock %}

{% block datebook_content %}
    
{% crispy form %}
{% endblock %}

datebook/templates/datebook/datebook_month_week.html
{% extends "datebook/base.html" %}
{% load i18n %}

{% block datebook_content %}

<ul class="datebook-calendar-month-week">{% for datekey, entry in weekdays %}
    <li class="item">
        <h3>{{ datekey|date:"d - l" }}</h3>
        <div class="container{% if not entry %} empty{% elif entry.vacation %} vacation{% endif %}">
        {% if entry %}
            {% if entry.vacation %}
                <p>Vacation</p>
            {% else %}
                <p class="working-hour">{{ entry.get_working_hours }}</p>
                <div class="content">{{ entry.content }}</div>
                <p class="length">{{ entry.get_elapsed_time }}</p>
            {% endif %}
            <p><a href="{% url 'datebook-author-day-edit' author=author year=datebook.period.year month=datebook.period.month day=datekey|date:"d" %}" class="button round secondary">{% trans 'Edit' %}</a></p>
        {% else %}
            <p><a href="{% url 'datebook-author-day-add' author=author year=datebook.period.year month=datebook.period.month day=datekey|date:"d" %}" class="button round secondary">{% trans 'Add' %}</a></p>
        {% endif %}
        </div>
    </li>
{% endfor %}</ul>
{% endblock %}

datebook/templates/datebook/datebook_week.html
{% extends "datebook/base.html" %}
{% load i18n %}

{% block datebook_content %}

<ul class="datebook-calendar-month-week">{% for datekey, entry in weekdays %}
    <li class="item" id="week-day-{{ datekey.day }}">
        <h3>{{ datekey|date:"d - l" }}</h3>
        <div class="container{% if not entry %} empty{% elif entry.vacation %} vacation{% endif %}">
        {% if entry %}
            {% if entry.vacation %}
                <p class="text-center"><em>Vacation</em></p>
            {% else %}
                <p class="working-hour">{{ entry.get_working_hours }}</p>
                <div class="content">{{ entry.content|linebreaks }}</div>
                <p class="length">{{ entry.get_elapsed_time }}</p>
            {% endif %}
            <p class="text-right"><a href="{% url 'datebook-author-day-edit' author=author year=datebook.period.year month=datebook.period.month day=datekey|date:"d" %}" class="button round success">{% trans 'Edit' %} <i class="icon-pencil"></i></a></p>
        {% else %}
            <p class="text-right"><a href="{% url 'datebook-author-day-add' author=author year=datebook.period.year month=datebook.period.month day=datekey|date:"d" %}" class="button round success">{% trans 'Add' %} <i class="icon-add-circle"></i></a></p>
        {% endif %}
        </div>
    </li>
{% endfor %}</ul>
{% endblock %}

datebook/templates/datebook/datebook_year.html
{% extends "datebook/base.html" %}
{% load i18n %}

{% block datebook_content %}
<div class="datebook-calendar-year">{% for name, datebook in datebooks_map %}
    <div class="small-12 medium-3 columns{% if not datebook %} empty{% endif %}">
        <div class="panel radius text-center">
            <h3>{{ name|capfirst }}</h3>
            {% if datebook %}
                <p>
                    <a href="{% url 'datebook-author-month' author=author year=datebook.period.year month=datebook.period.month %}" class="button">{{ datebook.dayentry_set.count }} entries</a>
                </p>
            {% else %}
                <p>
                    <a href="#" class="button secondary" data-reveal-id="new-datebook-{{ name }}">Create it</a>
                </p>
            {% endif %}
        </div>
    </div>
{% endfor %}</div>
{% endblock %}

{% block foot_more_js %}{{ block.super }}
{% for name, datebook in datebooks_map %}{% if not datebook %}
<div id="new-datebook-{{ name }}" class="reveal-modal text-center tiny" data-reveal>
    <h3>Create a new datebook<h3>
    <p>This will create a datebook for <strong>{{ name|capfirst }} {{ year }}</strong>, confirm this.</p>
    <p><a href="{% url 'datebook-author-month-add' author=author year=year month=forloop.counter %}" class="radius success button">I confirm</a></p>
    <a class="close-reveal-modal">&#215;</a>
</div>
{% endif %}{% endfor %}
{% endblock %}

datebook/templates/datebook/include_css.html
{% load assets %}{% assets "datebook_app_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
{% endassets %}
{% comment %}<link rel="stylesheet" href="{{ STATIC_URL }}css/datebook_app.css">{% endcomment %}

datebook/templates/datebook/include_js.html
{% load assets %}{% assets "datebook_app_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% comment %}<script type="text/javascript" src="{{ STATIC_URL }}js/datebook_app.min.js"></script>{% endcomment %}

datebook/templates/datebook/index.html
{% extends "datebook/base.html" %}
{% load i18n %}

{% block datebook_content %}
<div class="row">
    <div class="small-12 medium-6 large-4 columns">
        <p><a href="{% url 'datebook:current-month' author=user %}" class="button large expand radius"><i class="icon-calendar"></i> {% blocktrans %}See current month{% endblocktrans %}</a></p>
    </div>
    <div class="small-12 medium-6 large-4 columns">
        <p><a href="{% url 'datebook:day-models' author=user %}" class="button large expand radius"><i class="icon-insert-template"></i> {% blocktrans %}Manage your models{% endblocktrans %}</a></p>
    </div>
    <div class="small-12 medium-12 large-4 columns">
        <p><a href="{% url 'datebook:current-day' author=user %}" class="button success large expand radius"><i class="icon-pencil"></i> {% blocktrans %}Fill your current day{% endblocktrans %}</a></p>
    </div>
</div>
<hr/>

<ul class="inline-list">
    {% spaceless %}{% for item in object_list %}
        <li>
            <a href="{% url 'datebook:author-detail' author=item.author__username %}" class="button small radius">{{ item.author__username }}</a>
            {% comment %}<p>Updated on {{ item.modified|timesince }}</p>{% endcomment %}
        </li>
    {% endfor %}{% endspaceless %}
        {% if user.is_superuser or perms.datebook.add_datebook %}<li>
            <a href="{% url 'datebook:create' %}" class="button success small radius"><i class="icon-add-circle"></i> {% blocktrans %}Open a new datebook for a new user{% endblocktrans %}</a>
        </li>{% endif %}
</ul>
 {% endblock %}

datebook/templates/datebook/year.html
{% extends "datebook/base.html" %}
{% load i18n %}

{% block datebook_content %}
<div class="datebook-calendar-year">{% for month_date, month_datebook in datebooks_map %}
    <div class="flex-column radius text-center{% if not month_datebook %} empty{% endif %}{% if month_date.year == today.year and month_date.month == today.month %} current{% endif %}">
        <div class="inner">
            <h3>{{ month_date|date:"F" }}</h3>
            {% if month_datebook %}
                <p>
                    {% with month_datebook.dayentry_set.count as entries_counter %}
                    <a href="{% url 'datebook:month-detail' author=author year=month_datebook.period.year month=month_datebook.period.month %}" class="button{% if not entries_counter %} secondary{% endif %}">
                        {% if entries_counter > 0 %}
                            {% blocktrans count counter=entries_counter %}{{ counter }} day{% plural %}{{ counter }} days{% endblocktrans %}
                        {% else %}
                            {% trans "Empty" %}
                        {% endif %}
                    </a>
                    {% endwith %}
                </p>
            {% else %}
                {% if user == author or user.is_superuser or perms.datebook.add_datebook %}
                    <p><a href="#" class="button success" data-reveal-id="new-datebook-{{ month_date.month }}">{% trans "Create it" %}</a></p>
                {% else %}
                    <p class="empty text-center">{% trans "Empty" %}</p>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endfor %}</div>
{% endblock %}

{% block foot_more_js %}{{ block.super }}{% if user == author or user.is_superuser or perms.datebook.add_datebook %}
{% for month_date, month_datebook in datebooks_map %}{% if not month_datebook %}
<div id="new-datebook-{{ month_date.month }}" class="reveal-modal text-center tiny" data-reveal>
    <h3>{% trans "Create a new datebook" %}</h3>
    <p>{% blocktrans with name=month_date|date:"F" year=month_date.year %}This will create a datebook for <strong>{{ name }} {{ year }}</strong>, confirm this.{% endblocktrans %}</p>
    <p><a href="{% url 'datebook:month-add' author=author year=year month=forloop.counter %}" class="radius success button">{% trans "I confirm" %}</a></p>
    <a class="close-reveal-modal">&#215;</a>
</div>
{% endif %}{% endfor %}
{% endif %}{% endblock %}